from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page()
    page.goto('https://chat.deepseek.com', timeout=30000)
    page.wait_for_timeout(5000)
    print('=== 页面标题 ===')
    print(page.title())
    print()
    print('=== textarea 数量 ===')
    print(page.locator('textarea').count())
    print()
    print('=== input 元素 ===')
    inputs = page.locator('input')
    print(f'共 {inputs.count()} 个')
    for i in range(min(inputs.count(), 5)):
        t = inputs.nth(i).get_attribute('type')
        p = inputs.nth(i).get_attribute('placeholder')
        print(f'  input[{i}]: type={t}, placeholder={p}')
    print()
    print('=== role=textbox 元素 ===')
    textboxes = page.locator('[role="textbox"]')
    print(f'共 {textboxes.count()} 个')
    for i in range(min(textboxes.count(), 3)):
        tag = textboxes.nth(i).evaluate('el => el.tagName')
        cls = textboxes.nth(i).get_attribute('class')
        print(f'  textbox[{i}]: tag={tag}, class={cls}')
    print()
    print('=== 页面可见文本前500字符 ===')
    print(page.locator('body').inner_text()[:500])
    browser.close()
